apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kimhae
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 172.30.1.70/kimhae/frontend:1.0.1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  namespace: kimhae
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
