apiVersion: v1
kind: Namespace
metadata:
 name: kimhae
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: db-config
 namespace: kimhae
data:
 DB_URL: 172.30.1.70:27017
 DB_USER: root
 DB_PASS: mongodb
 DB_DATABASE: kimhae
 DB_COLLECTION: wifi
