---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: dbserver
 namespace: kimhae
spec:
 replicas: 2
 selector:
  matchLabels:
   app: dbserver
 template:
  metadata:
   labels:
    app: dbserver
  spec:
   containers:
    - image: "172.30.1.70/kimhae/dbserver:0.1.1"
      name: dbserver
      ports:
       - containerPort: 5000
      envFrom:
       - configMapRef:
          name: db-config
   imagePullSecrets:
    - name: harbor
---
apiVersion: v1
kind: Service
metadata:
 name: dbserver-service
 namespace: kimhae
spec:
 type: ClusterIP
 selector:
  app: dbserver
 ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
